/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.here.fox;

import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import com.here.fox.service.impl.RoutingServiceFactory;
import com.here.fox.service.impl.RoutingServiceFactory.RoutingAlg;
import com.here.fox.util.CommandLineProcessor;

/**
 * Main App implementation, designed for command line usage.
 * Will start the command line processor into a different thread and then wait indefinitely.
 * @author ramysiha
 *
 */
public class App {

	public static void main(String[] args) throws InterruptedException, ExecutionException {
		CommandLineProcessor cmdProcessor = new CommandLineProcessor(
				RoutingServiceFactory.createRoutingServiceFactor(RoutingAlg.DIJKSTRAS));
		ExecutorService executor = Executors.newSingleThreadExecutor();
		try {
			executor.submit(cmdProcessor).get();
		} catch(ExecutionException e) {
			e.printStackTrace();
			executor.shutdown();
		}
	}
}
